version: '3.8'

services:
  backend:
    build: ./backend

    image: zororor/dockercomposedemo-backend:latest
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend

    image: zororor/dockercomposedemo-frontend:latest
    depends_on:
      - backend
    ports:
      - '3000:3000'
